CREATE TABLE IF NOT EXISTS users (
	user_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (user_id),
	CONSTRAINT user_unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
	request_id bigint NOT NULL,
	description varchar(1000) NOT NULL,
	requestor_id bigint NOT NULL,
	CONSTRAINT requests_pk PRIMARY KEY (request_id),
	CONSTRAINT requests_users_fk FOREIGN KEY (requestor_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
	item_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	description varchar(1000) NOT NULL,
	available boolean NOT NULL,
	owner_id bigint NOT NULL,
	request_id bigint NULL,
	CONSTRAINT items_pk PRIMARY KEY (item_id),
	CONSTRAINT items_users_fk FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT items_requests_fk FOREIGN KEY (request_id) REFERENCES requests(request_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings (
	booking_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	start_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	item_id bigint NOT NULL,
	booker_id bigint NOT NULL,
	status varchar(100) NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (booking_id),
	CONSTRAINT bookings_users_fk FOREIGN KEY (booker_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
	comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	text varchar(1000) NOT NULL,
	item_id bigint NOT NULL,
	author_id bigint NOT NULL,
	create_date timestamp without time zone NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (comment_id),
	CONSTRAINT comments_users_fk FOREIGN KEY (author_id) REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);